name: forfun_teller
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_gradient_animation_text: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_ui_auth: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
