name: forfun_teller
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_gradient_animation_text: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_ui_auth: ^1.6.3
  firebase_core: ^2.15.1
  provider: ^6.0.5
  font_awesome_flutter: ^10.5.0
  flutter_styled_toast: ^2.1.3
  flutter_spinkit: ^5.2.0
  convex_bottom_bar: ^3.2.0
  flutter_onboarding_slider: ^1.0.9
  persistent_bottom_nav_bar: ^5.0.2
  flutter_flip_card: ^0.0.4
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  page_transition: ^2.0.9
  firebase_storage: ^11.2.6
  flutter_slider_drawer: ^2.1.3
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
